#** Data Collection**

---

In [ ]:
#importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#loading the datset
data = pd.read_csv("hypertension_data.csv")

In [ ]:
#previewing the dataset
data.head()

,C,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,Male,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
1,Female,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
2,Male,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
3,Female,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
4,Male,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)

In [ ]:
#size of the dataset
data.shape

(1825, 14)

In [ ]:
#dataset info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   C                1825 non-null   object
 1   Age              1825 non-null   object
 2   History          1825 non-null   object
 3   Patient          1825 non-null   object
 4   TakeMedication   1825 non-null   object
 5   Severity         1825 non-null   object
 6   BreathShortness  1825 non-null   object
 7   VisualChanges    1825 non-null   object
 8   NoseBleeding     1825 non-null   object
 9   Whendiagnoused   1825 non-null   object
 10  Systolic         1825 non-null   object
 11  Diastolic        1825 non-null   object
 12  ControlledDiet   1825 non-null   object
 13  Stages           1825 non-null   object
dtypes: object(14)
memory usage: 199.7+ KB

# **DATA PREPARATION**

---

**1. Handling Missing Values**

In [ ]:
#checking for missing values
data.isnull().sum()

C                  0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

**2. Data Type Correction**

In [ ]:
#Checking column name
data.columns

Index(['C', 'Age', 'History', 'Patient', 'TakeMedication', 'Severity',
       'BreathShortness', 'VisualChanges', 'NoseBleeding', 'Whendiagnoused',
       'Systolic', 'Diastolic', 'ControlledDiet', 'Stages'],
      dtype='object')

In [ ]:
#Renaming the column
data.rename(columns={'C':'Gender'}, inplace = True)

In [ ]:
#Verification
data.columns

Index(['Gender', 'Age', 'History', 'Patient', 'TakeMedication', 'Severity',
       'BreathShortness', 'VisualChanges', 'NoseBleeding', 'Whendiagnoused',
       'Systolic', 'Diastolic', 'ControlledDiet', 'Stages'],
      dtype='object')

**3. Inconsistency Corrections**

In [ ]:
#checking unqiue values
categorical_cols = [
'Gender','History','Patient','TakeMedication','Severity',
'BreathShortness','VisualChanges','NoseBleeding',
'Whendiagnoused','ControlledDiet','Stages'
]

for col in categorical_cols:
    print(col, ":", data[col].unique())

Gender : ['Male' 'Female']
History : ['Yes' 'No']
Patient : ['No' 'Yes']
TakeMedication : ['No' 'Yes ' 'Yes']
Severity : ['Mild' 'Sever' 'Moderate']
BreathShortness : ['No' 'Yes']
VisualChanges : ['No' 'Yes']
NoseBleeding : ['No ' 'No' 'Yes']
Whendiagnoused : ['<1 Year' '1 - 5 Years' '>5 Years']
ControlledDiet : ['No' 'Yes']
Stages : ['HYPERTENSION (Stage-1)' 'HYPERTENSION (Stage-2)' 'HYPERTENSIVE CRISIS'
 'HYPERTENSION (Stage-2).' 'HYPERTENSIVE CRISI' 'NORMAL']

In [ ]:
#remove extra spaces
for col in categorical_cols:
    data[col] = data[col].astype(str).str.strip()

#fix severity spelling
data['Severity'] = data['Severity'].replace('Sever','Severe')

#fix stage labels
data['Stages'] = data['Stages'].replace({
'HYPERTENSION (Stage-2).':'HYPERTENSION (Stage-2)',
'HYPERTENSIVE CRISI':'HYPERTENSIVE CRISIS'
})

In [ ]:
#verification
for col in categorical_cols:
    print(col, ":", data[col].unique())

Gender : ['Male' 'Female']
History : ['Yes' 'No']
Patient : ['No' 'Yes']
TakeMedication : ['No' 'Yes']
Severity : ['Mild' 'Severe' 'Moderate']
BreathShortness : ['No' 'Yes']
VisualChanges : ['No' 'Yes']
NoseBleeding : ['No' 'Yes']
Whendiagnoused : ['<1 Year' '1 - 5 Years' '>5 Years']
ControlledDiet : ['No' 'Yes']
Stages : ['HYPERTENSION (Stage-1)' 'HYPERTENSION (Stage-2)' 'HYPERTENSIVE CRISIS'
 'NORMAL']

**4. Duplicate Removal**

In [ ]:
#removing duplicates
data.shape

(1825, 14)

In [ ]:
#no. of duplicated row
data.duplicated().sum()

np.int64(477)

In [ ]:
#removing duplicated row
data = data.drop_duplicates()

In [ ]:
#verification
data.shape

(1348, 14)

#**CATEGORIAL DATA ENCODING**

---

**1. Defining Features**

In [ ]:
#Defining Nominal Features
nominal_features = ['Gender','History','Patient','TakeMedication',
'BreathShortness','VisualChanges','NoseBleeding',
'ControlledDiet']

#Defining Odinal Features
ordinal_features = ['Age','Severity','Whendiagnoused','Systolic','Diastolic']

#Defining Target Featue
target_feature = ['Stages']

**2. Encoding Features**

In [ ]:
#Encoding Binary Features
for col in nominal_features:
    if set(data[col].unique()) == set(['Yes','No']):
        data[col] = data[col].map({'No':0,'Yes':1})

#Encoding Genders
data['Gender'] = data['Gender'].map({'Male':0,'Female':1})

#Encoding Age Groups
data['Age'] = data['Age'].map({'18-34':1,'35-50':2,'51-64':3,'65+':4})

#Encoding Severity
data['Severity'] = data['Severity'].replace({'Mild':0,'Moderate':1,'Severe':2})

#Encoding Diagnosis Time
data['Whendiagnoused'] = data['Whendiagnoused'].map({'<1 Year':1,'1 - 5 Years':2,'>5 Years':3})

#Encoding Blood Pressure
data['Systolic'] = data['Systolic'].map({'100 - 110':0,'111 - 120':1,'121 - 130':2,'130+':3})

data['Diastolic'] = data['Diastolic'].map({'70 - 80':0,'81 - 90':1,'91 - 100':2,'100+':3})

#Encoding Target Variable
data['Stages'] = data['Stages'].map({'NORMAL':0,'HYPERTENSION (Stage-1)':1,'HYPERTENSION (Stage-2)':2,'HYPERTENSIVE CRISIS':3})

/tmp/ipykernel_190/1288717862.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Severity'] = data['Severity'].replace({'Mild':0,'Moderate':1,'Severe':2})

**3. Aplying and Verfying**

In [ ]:
#Applying Feature Scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
ordinal_features = ['Age','Severity','Whendiagnoused','Systolic','Diastolic']

data[ordinal_features] = scaler.fit_transform(data[ordinal_features])

#Verification
data.head()
data.dtypes

Gender               int64
Age                float64
History              int64
Patient              int64
TakeMedication       int64
Severity           float64
BreathShortness      int64
VisualChanges        int64
NoseBleeding         int64
Whendiagnoused     float64
Systolic           float64
Diastolic          float64
ControlledDiet       int64
Stages               int64
dtype: object

#**DATA SPLITTING**

---

In [ ]:
#importing Train Test Split
from sklearn.model_selection import train_test_split

#seperating features and target
X = data.drop('Stages', axis=1)
y = data['Stages']

#performing train/test split
X_train , X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42, stratify=y)

In [ ]:
#Verifying Split
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 1078
Testing samples: 270

# **Algorithm Implementation and Comparison**

---

In [ ]:
#importing libraries
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#accuracy dictionary
accuracy = {}

**1. Logistic Regression**

In [ ]:
log_reg = LogisticRegression(max_iter=1000)

# Check for NaNs before fitting the model
if X_train.isnull().sum().sum() > 0:
    print("NaNs found in X_train. Handling missing values...")
    # For simplicity, we'll fill NaNs with the mean of the column.
    # A more sophisticated imputation strategy might be needed depending on the data.
    X_train = X_train.fillna(X_train.mean())
    X_test = X_test.fillna(X_test.mean())

log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)

print("Logistic Regression:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['Logistic Regression'] = accuracy_score(y_test, y_pred)

NaNs found in X_train. Handling missing values...
Logistic Regression:
Accuracy: 0.9407407407407408
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       120
           2       1.00      0.80      0.89        79
           3       0.75      1.00      0.86        48

    accuracy                           0.94       270
   macro avg       0.94      0.95      0.94       270
weighted avg       0.96      0.94      0.94       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 120   0   0]
 [  0   0  63  16]
 [  0   0   0  48]]

**2. Decision Tree**

In [ ]:
decisionTree = DecisionTreeClassifier()

decisionTree.fit(X_train, y_train)

y_pred = decisionTree.predict(X_test)

print("Decision Tree:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['Decision Tree'] = accuracy_score(y_test, y_pred)

Decision Tree:
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       120
           2       1.00      1.00      1.00        79
           3       1.00      1.00      1.00        48

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 120   0   0]
 [  0   0  79   0]
 [  0   0   0  48]]

**3. Random Forest**

In [ ]:
randomforest = RandomForestClassifier()

randomforest.fit(X_train, y_train)

y_pred = randomforest.predict(X_test)

print("Random Forest:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['Random Forest'] = accuracy_score(y_test, y_pred)

Random Forest:
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       120
           2       1.00      1.00      1.00        79
           3       1.00      1.00      1.00        48

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 120   0   0]
 [  0   0  79   0]
 [  0   0   0  48]]

**4. Support Vector Machine (SVM)**

In [ ]:
svm = SVC()

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

print("SVM:")

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred))

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['SVM'] = accuracy_score(y_test, y_pred)

SVM:
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       120
           2       1.00      1.00      1.00        79
           3       1.00      1.00      1.00        48

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 120   0   0]
 [  0   0  79   0]
 [  0   0   0  48]]

**5. K-Nearest Neighbors (KNN)**

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("KNN:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['KNN'] = accuracy_score(y_test, y_pred)

KNN:
Accuracy: 0.9703703703703703
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.65      0.79        23
           1       0.94      1.00      0.97       120
           2       1.00      1.00      1.00        79
           3       1.00      1.00      1.00        48

    accuracy                           0.97       270
   macro avg       0.98      0.91      0.94       270
weighted avg       0.97      0.97      0.97       270

Confusion Matrix:
 [[ 15   8   0   0]
 [  0 120   0   0]
 [  0   0  79   0]
 [  0   0   0  48]]

**6. Ridge Classifier**

In [ ]:
RC = RidgeClassifier()

RC.fit(X_train, y_train)

y_pred = RC.predict(X_test)

print("RidgeClassifier:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['RidgeClassifier'] = accuracy_score(y_test, y_pred)

RidgeClassifier:
Accuracy: 0.8888888888888888
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.39      0.56        23
           1       0.90      1.00      0.94       120
           2       1.00      0.80      0.89        79
           3       0.75      1.00      0.86        48

    accuracy                           0.89       270
   macro avg       0.91      0.80      0.81       270
weighted avg       0.91      0.89      0.88       270

Confusion Matrix:
 [[  9  14   0   0]
 [  0 120   0   0]
 [  0   0  63  16]
 [  0   0   0  48]]

**7. Gaussian Naive Bayes (Selected Model)**

In [ ]:
naive_bayes = GaussianNB()

naive_bayes.fit(X_train, y_train)

y_pred = naive_bayes.predict(X_test)

print("Naive Bayes:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

accuracy['Naive Bayes'] = accuracy_score(y_test, y_pred)

Naive Bayes:
Accuracy: 0.8444444444444444
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       120
           2       1.00      0.47      0.64        79
           3       0.53      1.00      0.70        48

    accuracy                           0.84       270
   macro avg       0.88      0.87      0.83       270
weighted avg       0.92      0.84      0.84       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 120   0   0]
 [  0   0  37  42]
 [  0   0   0  48]]

#**MODEL COMPARISION TABLE**

In [ ]:
accuracy_df = pd.DataFrame(list(accuracy.items()), columns=['Model','Accuracy'])

accuracy_df = accuracy_df.sort_values(by='Accuracy', ascending=False)

accuracy_df

                 Model  Accuracy
1        Decision Tree  1.000000
2        Random Forest  1.000000
3                  KNN  0.970370
0  Logistic Regression  0.940741
4      RidgeClassifier  0.888889
5          Naive Bayes  0.844444